// Chip-race chart from a PokerNow log, emitted as an embeddable fragment and
// injected into that game's page between CHIP-RACE markers. Part of the
// monthly publish (docs/publishing.md); the chart lives ON the game page
// (spec 2026-08-17 §7), styled by site/styles.css (.chip-race rules).
// Run: bun tools/chip-race.ts <log.csv> --date YYYY-MM-DD --start 5000 --inject site/games/<date>/index.html
//      (or --out <file> to write the bare fragment for inspection)
// Old /games/<date>/chip-race.html URLs redirect to the game page via
// site/_redirects; this tool no longer writes standalone pages.
import { parseRows, stackSnapshots, handCount, entryCount } from "./lib/pokernow";

const PALETTE = ["#c9a227", "#2b5d9e", "#b06c3f", "#8a8d91", "#5e8c61", "#9e2b5d", "#4a4e57"];

// The injection markers in a game page. Everything between them is generated;
// hand edits there are overwritten on the next inject, which is the point:
// the chart must come from the log, never from a hand edit.
export const MARK_START = "<!-- CHIP-RACE:START (generated by tools/chip-race.ts --inject; never hand-edit between the markers) -->";
export const MARK_END = "<!-- CHIP-RACE:END -->";

// Builds the embeddable chart fragment: a <figure class="chip-race"> holding
// the meta line, the SVG (axes derived from the log: x = hand count, y = max
// observed stack, so nothing is ever inherited from a previous month), and a
// color-key legend. Throws only via parse errors on a malformed log.
export function buildChipRaceFragment(csv: string, opts: { date: string; startingStack: number }): string {
  const rows = parseRows(csv);
  const snaps = stackSnapshots(rows);
  const hands = handCount(rows);
  const final = snaps[snaps.length - 1].stacks;
  const entries = entryCount(final, opts.startingStack);

  const players = [...new Set(snaps.flatMap(s => Object.keys(s.stacks)))];
  const maxChips = Math.max(...snaps.flatMap(s => Object.values(s.stacks)));
  const W = 720, H = 400, PAD = 40;
  const x = (hand: number) => PAD + (hand / Math.max(hands, 1)) * (W - 2 * PAD);
  const y = (chips: number) => H - PAD - (chips / maxChips) * (H - 2 * PAD);

  const lines = players.map((p, i) => {
    const pts = snaps
      .filter(s => p in s.stacks)
      .map(s => `${x(s.hand).toFixed(1)},${y(s.stacks[p]).toFixed(1)}`)
      .join(" ");
    return `  <polyline fill="none" stroke="${PALETTE[i % PALETTE.length]}" stroke-width="2.5" points="${pts}"><title>${p}</title></polyline>`;
  }).join("\n");

  const legend = players.map((p, i) =>
    `<span class="key"><span class="swatch" style="background:${PALETTE[i % PALETTE.length]}"></span>${p}</span>`
  ).join("\n    ");

  return `<figure class="chip-race">
  <p class="meta">Chip race: ${opts.date}. ${entries} entries, ${hands} hands.</p>
  <div class="wrap">
  <svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Chip counts per player over ${hands} hands">
    <line x1="${PAD}" y1="${H - PAD}" x2="${W - PAD}" y2="${H - PAD}" stroke="#8a8d91"/>
    <line x1="${PAD}" y1="${PAD}" x2="${PAD}" y2="${H - PAD}" stroke="#8a8d91"/>
${lines}
  </svg>
  </div>
  <figcaption class="chip-legend">
    ${legend}
  </figcaption>
</figure>`;
}

// Replaces the generated region of a game page with a fresh fragment.
// Throws when the markers are missing or ambiguous rather than guessing:
// a page without exactly one marker pair was not built from the shell in
// docs/publishing.md, and injecting into the wrong place would publish a
// chart nobody reviewed.
export function injectFragment(pageHtml: string, fragment: string): string {
  const starts = pageHtml.split(MARK_START).length - 1;
  const ends = pageHtml.split(MARK_END).length - 1;
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `expected exactly one CHIP-RACE marker pair, found ${starts} start / ${ends} end. ` +
      `Copy the newest game page shell (docs/publishing.md step 4) to get the markers.`
    );
  }
  const before = pageHtml.slice(0, pageHtml.indexOf(MARK_START) + MARK_START.length);
  const after = pageHtml.slice(pageHtml.indexOf(MARK_END));
  return `${before}\n${fragment}\n${after}`;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const flag = (n: string) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined; };
  const csv = await Bun.file(args[0]).text();
  const fragment = buildChipRaceFragment(csv, {
    date: flag("--date") ?? "unknown",
    startingStack: Number(flag("--start") ?? 5000),
  });
  const inject = flag("--inject");
  if (inject) {
    const page = await Bun.file(inject).text();
    await Bun.write(inject, injectFragment(page, fragment));
    console.log(`injected chip race into ${inject}`);
  } else {
    const out = flag("--out") ?? "chip-race-fragment.html";
    await Bun.write(out, fragment);
    console.log(`wrote ${out}`);
  }
}
