// Chip-race chart from one or more PokerNow logs, emitted as an embeddable
// fragment and injected into that game's page between CHIP-RACE markers.
// Part of the monthly publish (docs/publishing.md); the chart lives ON the
// game page (spec 2026-08-17 §7), styled by site/styles.css (.chip-race rules).
// Run: bun tools/chip-race.ts <log1.csv> [log2.csv ...] --date YYYY-MM-DD --start 5000 --inject site/games/<date>/index.html
//      (or --out <file> to write the bare fragment for inspection)
// A multi-table tournament (10+ players) exports one log per table; pass
// every table's log and the chart draws all of them on one clock, with the
// moment the tables merged marked. One log is the ordinary single-table game.
// Old /games/<date>/chip-race.html URLs redirect to the game page via
// site/_redirects; this tool no longer writes standalone pages.
import { mergeLogs, stackSnapshots, busts, handCount, entryCount } from "./lib/pokernow";
import { positionals, flag } from "./lib/args";

// Seven house colors. A game with more players than this (September 2026 had
// fourteen) cycles back to the first color with a dashed stroke, so two lines
// never look identical; the legend swatch carries the same dash.
const PALETTE = ["#c9a227", "#2b5d9e", "#b06c3f", "#8a8d91", "#5e8c61", "#9e2b5d", "#4a4e57"];
const DASH = "6,4";

// The injection markers in a game page. Everything between them is generated;
// hand edits there are overwritten on the next inject, which is the point:
// the chart must come from the log, never from a hand edit.
export const MARK_START = "<!-- CHIP-RACE:START (generated by tools/chip-race.ts --inject; never hand-edit between the markers) -->";
export const MARK_END = "<!-- CHIP-RACE:END -->";

const W = 720, H = 400, PAD = 40;
const HALF_HOUR = 30 * 60 * 1000;

// A log timestamp (UTC, as PokerNow writes it) as a Pacific clock time the
// way the site says times everywhere else: "8:43pm". The games are played
// in Pacific time whatever the log says; Intl handles daylight vs standard.
export function clockPT(iso: string): string {
  const s = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Los_Angeles", hour: "numeric", minute: "2-digit", hour12: true,
  }).format(new Date(iso));
  return s.replace(/\s/g, "").toLowerCase();
}

// "two tables" reads better than "2 tables" in the meta line; past what a
// club game could plausibly seat, digits are fine.
function countWord(n: number): string {
  return ["zero", "one", "two", "three", "four", "five", "six"][n] ?? String(n);
}

// Builds the embeddable chart fragment: a <figure class="chip-race"> holding
// the meta line, the SVG, and a color-key legend. Takes every table's log
// (one for an ordinary game). Throws only via parse errors on a malformed
// log, or ChipConservationError when the final stacks do not divide by the
// starting stack.
//
// The x axis is wall-clock time since the first stack snapshot, never hand
// number: tables run in parallel and each counts its own hands from #1, so
// time is the one axis they share. In a single log time and hand number are
// monotonic together, so a one-table chart keeps its shape. The y axis is
// the largest stack seen in the log, so nothing is ever inherited from a
// previous month. A bust ends its line at zero at the moment the player
// left; a rebuy shows as a jump back up, as before.
export function buildChipRaceFragment(csvs: string[], opts: { date: string; startingStack: number }): string {
  const { rows, tables, merges } = mergeLogs(csvs);
  const snaps = stackSnapshots(rows);
  const hands = handCount(rows);
  const final = snaps[snaps.length - 1].stacks;
  const entries = entryCount(final, opts.startingStack);
  const exits = busts(rows);

  const players = [...new Set(snaps.flatMap(s => Object.keys(s.stacks)))];
  const maxChips = Math.max(...snaps.flatMap(s => Object.values(s.stacks)));
  const ms = (iso: string) => Date.parse(iso);
  const t0 = ms(snaps[0].at);
  const tEnd = Math.max(ms(snaps[snaps.length - 1].at), ...exits.map(b => ms(b.at)));
  const span = Math.max(tEnd - t0, 1);
  const x = (t: number) => PAD + ((t - t0) / span) * (W - 2 * PAD);
  const y = (chips: number) => H - PAD - (chips / maxChips) * (H - 2 * PAD);
  const pt = (t: number, chips: number) => `${x(t).toFixed(1)},${y(chips).toFixed(1)}`;

  const lines = players.map((p, i) => {
    const points = [
      ...snaps.filter(s => p in s.stacks).map(s => ({ t: ms(s.at), chips: s.stacks[p] })),
      ...exits.filter(b => b.player === p).map(b => ({ t: ms(b.at), chips: 0 })),
    ].sort((a, b) => a.t - b.t);
    const pts = points.map(q => pt(q.t, q.chips)).join(" ");
    const dash = i >= PALETTE.length ? ` stroke-dasharray="${DASH}"` : "";
    return `  <polyline fill="none" stroke="${PALETTE[i % PALETTE.length]}" stroke-width="2.5"${dash} points="${pts}"><title>${p}</title></polyline>`;
  }).join("\n");

  // Ticks on the half hour of Pacific wall-clock time. Pacific time is a
  // whole number of hours from UTC, so half-hour boundaries coincide and the
  // arithmetic can stay in UTC milliseconds; only the label is converted.
  const ticks: string[] = [];
  for (let t = Math.ceil(t0 / HALF_HOUR) * HALF_HOUR; t <= tEnd; t += HALF_HOUR) {
    const tx = x(t).toFixed(1);
    ticks.push(
      `  <g class="tick"><line x1="${tx}" y1="${H - PAD}" x2="${tx}" y2="${H - PAD + 5}"/>` +
      `<text x="${tx}" y="${H - PAD + 18}" text-anchor="middle">${clockPT(new Date(t).toISOString())}</text></g>`
    );
  }

  // One dashed marker per table that closed, labelled with the clock time,
  // and a region label above the plot for each stretch of the night ("two
  // tables", then "final table"). The marker label sits on whichever side
  // of the line has room. Balancing moves between tables need no marker;
  // a moved player's line simply continues.
  const markers: string[] = [];
  if (merges.length) {
    const bounds = [t0, ...merges.map(ms), tEnd];
    for (let k = 0; k < bounds.length - 1; k++) {
      const cx = ((x(bounds[k]) + x(bounds[k + 1])) / 2).toFixed(1);
      const label = k < bounds.length - 2 ? `${countWord(tables - k)} tables` : "final table";
      markers.push(`  <text class="region" x="${cx}" y="${PAD - 10}" text-anchor="middle">${label}</text>`);
    }
    for (const m of merges) {
      const mx = x(ms(m));
      const left = mx > W / 2;
      markers.push(
        `  <g class="merge"><line x1="${mx.toFixed(1)}" y1="${PAD}" x2="${mx.toFixed(1)}" y2="${H - PAD}"/>` +
        `<text x="${(left ? mx - 6 : mx + 6).toFixed(1)}" y="${PAD + 14}" text-anchor="${left ? "end" : "start"}">tables merge ${clockPT(m)}</text></g>`
      );
    }
  }

  const legend = players.map((p, i) => {
    const cls = i >= PALETTE.length ? "swatch swatch--dashed" : "swatch";
    return `<span class="key"><span class="${cls}" style="background:${PALETTE[i % PALETTE.length]}"></span>${p}</span>`;
  }).join("\n    ");

  const across = tables > 1 ? ` across ${countWord(tables)} tables` : "";
  return `<figure class="chip-race">
  <p class="meta">Chip race: ${opts.date}. ${entries} entries, ${hands} hands${across}.</p>
  <div class="wrap">
  <svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Chip counts per player over ${hands} hands${across}">
    <line x1="${PAD}" y1="${H - PAD}" x2="${W - PAD}" y2="${H - PAD}" stroke="#8a8d91"/>
    <line x1="${PAD}" y1="${PAD}" x2="${PAD}" y2="${H - PAD}" stroke="#8a8d91"/>
${[...ticks, ...markers, lines].join("\n")}
  </svg>
  </div>
  <figcaption class="chip-legend">
    ${legend}
  </figcaption>
</figure>`;
}

// Replaces the generated region of a game page with a fresh fragment.
// Throws when the markers are missing or ambiguous rather than guessing:
// a page without exactly one marker pair was not built from the shell in
// docs/publishing.md, and injecting into the wrong place would publish a
// chart nobody reviewed.
export function injectFragment(pageHtml: string, fragment: string): string {
  const starts = pageHtml.split(MARK_START).length - 1;
  const ends = pageHtml.split(MARK_END).length - 1;
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `expected exactly one CHIP-RACE marker pair, found ${starts} start / ${ends} end. ` +
      `Copy the newest game page shell (docs/publishing.md step 4) to get the markers.`
    );
  }
  const before = pageHtml.slice(0, pageHtml.indexOf(MARK_START) + MARK_START.length);
  const after = pageHtml.slice(pageHtml.indexOf(MARK_END));
  return `${before}\n${fragment}\n${after}`;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const paths = positionals(args);
  if (!paths.length) {
    console.error("usage: bun tools/chip-race.ts <log1.csv> [log2.csv ...] --date YYYY-MM-DD [--start 5000] (--inject <page.html> | --out <fragment.html>)");
    process.exit(1);
  }
  const csvs = await Promise.all(paths.map(p => Bun.file(p).text()));
  const fragment = buildChipRaceFragment(csvs, {
    date: flag(args, "--date") ?? "unknown",
    startingStack: Number(flag(args, "--start") ?? 5000),
  });
  const inject = flag(args, "--inject");
  if (inject) {
    const page = await Bun.file(inject).text();
    await Bun.write(inject, injectFragment(page, fragment));
    console.log(`injected chip race (${paths.length} ${paths.length === 1 ? "log" : "logs"}) into ${inject}`);
  } else {
    const out = flag(args, "--out") ?? "chip-race-fragment.html";
    await Bun.write(out, fragment);
    console.log(`wrote ${out}`);
  }
}
